name: code-quality
run-name: ${{ github.actor }} - code-quality
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Build all modules
        run: npm ci
          
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39
        with:
          files: '**/*.ts'

      - name: Lint all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "linting file: $file"
            npx eslint $file
          done
