name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    name: "Publish to npm registry"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - run: npm config set registry https://registry.npmjs.org/
      - run: npm ci

      - run: npm test

      - run: npm run deploy

      - run: rm -f .npmrc

      - uses: JS-DevTools/npm-publish@4b07b26a2f6e0a51846e1870223e545bae91c552
        if: github.event_name == 'release'
        with:
          token: ${{ secrets.NPM_PUBLISH }}
          registry: "https://registry.npmjs.org"
          package: deploy
