name: test
run-name: ${{ github.actor }} - test
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        runs-on: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - run: npm ci

      - run: npm test