name: test
run-name: ${{ github.actor }} - test
on: [pull_request, push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'pnpm'

      - run: node --version
      - run: npm --version

      - run: pnpm install

      - run: npm test

      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: ${{ matrix.os }}
      #     path: test/build-engine
